export const tk = {
  common: {
    loading: 'Ýüklenýär…',
    saving: 'Saklanýar…',
    saved: 'Saklandy',
    save: 'Sakla',
    cancel: 'Goý bes et',
    confirm: 'Tassykla',
    delete: 'Poz',
    edit: 'Üýtgetmek',
    add: 'Goş',
    create: 'Döret',
    update: 'Täzele',
    close: 'Ýap',
    search: 'Gözle…',
    filter: 'Süz',
    apply: 'Ulan',
    reset: 'Başlangyja getir',
    refresh: 'Täzele',
    next: 'Indiki',
    previous: 'Öňki',
    page: 'Sahypa',
    of: '/',
    yes: 'Hawa',
    no: 'Ýok',
    actions: 'Hereketler',
    status: 'Ýagdaý',
    name: 'Ady',
    email: 'Email',
    role: 'Rol',
    date: 'Senesi',
    type: 'Görnüşi',
    target: 'Niýet',
    none: 'Maglumat ýok',
    empty: 'Boş',
    error: 'Säwlik',
    success: 'Şowly',
    warning: 'Duýduryş',
    info: 'Maglumat',
    submit: 'Iber',
    back: 'Yza',
    selected: 'saýlandy',
    selectAll: 'Hemmesini saýla',
    clearSelection: 'Saýlamany aýyr',
    copy: 'Göçür',
    copied: 'Göçürildi',
    runNow: 'Häzir işlet',
    view: 'Görmek',
    details: 'Jikme-jiklikler',
    description: 'Düşündiriş',
    optional: 'Hökmany däl',
    required: 'Hökmany',
  },
  auth: {
    loginTitle: 'Ulgama gir',
    registerTitle: 'Hasap döret',
    forgotTitle: 'Paroly täzeden goý',
    resetTitle: 'Täze parol',
    haveAccount: 'Eýýäm hasabyňyz barmy?',
    noAccount: 'Ýa-da',
    createAccount: 'täze hasap döret',
    loginLink: 'Giriş ediň',
    forgotLink: 'Paroly unutdyňyzmy?',
    backToLogin: 'Giriş sahypasyna gaýt',
    emailPlaceholder: 'Email salgysy',
    usernamePlaceholder: 'Ulanyjy ady',
    passwordPlaceholder: 'Parol',
    tokenPlaceholder: 'Token',
    newPasswordPlaceholder: 'Täze parol',
    loginBtn: 'Giriş',
    loginingIn: 'Girilýär…',
    registerBtn: 'Hasap döret',
    creating: 'Döredilýär…',
    sendLink: 'Baglanyşyk iber',
    sending: 'Iberilýär…',
    updatePassword: 'Paroly täzele',
    accountCreated: 'Hasabyňyz döredildi! Giriş edip bilersiňiz.',
    linkSent: 'Eger email tapylan bolsa, baglanyşyk iberildi.',
    passwordUpdated: 'Parol täzelendi. Giriş edip bilersiňiz.',
    forgotHint: 'Emailiňize tassyklama baglanyşygy iberiler.',
    resetHint: 'Aşakda täze paroly giriziň.',
    loginFailed: 'Giriş şowsuz tamamlandy.',
    registerFailed: 'Hasap döretmek şowsuz tamamlandy.',
  },
  nav: {
    home: 'Baş sahypa',
    blogs: 'Bloglar',
    docs: 'Dokumentasiýa',
    login: 'Giriş',
    register: 'Hasap',
    getStarted: 'Başla',
    logout: 'Çykmak',
    dashboard: 'Panel',
    overview: 'Umumy',
    targets: 'Niýetlerim',
    scans: 'Skan netijeleri',
    vulnerabilities: 'Zelelilikler',
    analytics: 'Analitika',
    schedules: 'Tertipler',
    advanced: 'Goşmaça skanlar',
    profile: 'Profil',
    users: 'Ulanyjylar',
    settings: 'Sazlamalar',
    auditLogs: 'Audit ýazgylary',
    blogPosts: 'Blog ýazgylary',
    docsPages: 'Dokum. sahypalary',
    system: 'Ulgam',
    apiConsole: 'API Konsol',
    devTools: 'Geliştirici gurallary',
    publicSite: 'Açyk sahypa',
    adminPanel: 'Admin Panel',
  },
  targets: {
    title: 'Niýetlerim',
    subtitle: 'Gözegçilik etmek isleýän domenleriňizi we IP salgylaryňyzy dolandyryň.',
    addNew: 'Täze niýet goş',
    addNow: 'Häzir niýet goş',
    empty: 'Häzirlikçe niýet ýok',
    emptyHint: 'Zelelilikleri skanlemek üçin ilkinji domeniňizi ýa-da IP salgyňyzy goşuň.',
    nameAddress: 'Ady / Salgysy',
    owner: 'Eýesi',
    created: 'Döredildi',
    nameLabel: 'Niýetiň ady',
    namePlaceholder: 'Mysal: Meniň saýtym',
    addressLabel: 'Niýet salgysy (Domen ýa-da IP)',
    addressPlaceholder: 'Mysal: example.com',
    editTitle: 'Niýeti üýtget',
    newTitle: 'Täze niýet',
    active: 'Aktiw',
    inactive: 'Aktiw däl',
    verified: 'Tassyklanan',
    confirmDelete: 'Bu niýeti hakykatdanam pozmakçymy?',
    saveFailed: 'Niýet saklanmady.',
    scanStarted: 'Skanlama başlady',
    scanFailed: 'Skanlama başlap bilmedi.',
    verifyTitle: 'Eýeçiligi tassykla',
    verifyMethod: 'Tassyklama usuly',
    verifyDns: 'DNS TXT ýazgysy',
    verifyHttp: 'HTTP faýly',
    verifyMeta: 'HTML meta-teg',
    verifyToken: 'Tassyklama nyşany',
    verifyDnsHint: 'Domeniňize aşakdaky TXT ýazgysyny goşuň, soň "Tassykla" basyň.',
    verifyHttpHint: 'Domeniňiziň kökünde aşakdaky atly faýly ýerleşdiriň.',
    verifyMetaHint: 'Domeniň <head> bölümine aşakdaky meta-tegi goýuň.',
    verifyOk: 'Eýeçilik tassyklandy.',
    verifyFailed: 'Tassyklama başartmady.',
    assignTitle: 'Eýe belle',
    assignUserId: 'Eýäniň ID-si',
    assignFailed: 'Eýe bellenilmedi.',
    runScan: 'Skanlamaga başla',
  },
  scans: {
    title: 'Skan netijeleri',
    subtitle: 'Niýetleriňiziň üstünden geçirilen ähli skanlamalaryň taryhy.',
    newScan: 'Täze skan',
    scanId: 'Skan ID',
    empty: 'Skan ýok.',
    type: 'Görnüşi',
    created: 'Döredildi',
    searchPlaceholder: 'Niýet boýunça gözle…',
    allStatuses: 'Hemme ýagdaýlar',
    statusPending: 'Garaşýar',
    statusRunning: 'Işleýär',
    statusCompleted: 'Tamamlandy',
    statusFailed: 'Başartmady',
    statusCancelled: 'Goý bes edildi',
    selectTarget: 'Niýet saýla…',
    typeLabel: 'Skan görnüşi',
    typeFull: 'Doly',
    typeQuick: 'Çalt',
    typeApi: 'API audit',
    typePort: 'Port skan',
    createFailed: 'Skan döretmek başartmady.',
    runStarted: 'Skan #{id} işe başlady.',
    runFailed: 'Skan başlap bilmedi.',
    detailTitle: 'Skan jikme-jikligi',
    progress: 'Ösüş',
    duration: 'Dowamlylygy',
    findings: 'Tapyndylar',
    logs: 'Ýazgylar',
  },
  vulns: {
    title: 'Zelelilikler',
    subtitle: 'Ähli skanlamalardan tapylan zelelilikler.',
    listMode: 'Sanaw',
    owaspMode: 'OWASP toparlama',
    severityFilter: 'Howp derejesi',
    allSeverities: 'Hemme derejeler',
    statusFilter: 'Ýagdaý',
    allStatuses: 'Hemme ýagdaýlar',
    sevCritical: 'Kritiki',
    sevHigh: 'Ýokary',
    sevMedium: 'Orta',
    sevLow: 'Pes',
    sevInfo: 'Maglumat',
    statusOpen: 'Açyk',
    statusInProgress: 'Işlenilýär',
    statusResolved: 'Çözüldi',
    statusClosed: 'Ýapyk',
    statusFalsePositive: 'Ýalan-pozitiw',
    titleCol: 'Ady',
    owaspCol: 'OWASP',
    markFp: 'Ýalan-pozitiw bellän',
    lifecycle: 'Status üýtgetmek',
    lifecycleTitle: 'Statusy täzele',
    noteLabel: 'Bellik',
    updateFailed: 'Üýtgemedi.',
    empty: 'Zelelilik tapylmady.',
    cvss: 'CVSS bali',
    cwe: 'CWE',
    affectedUrl: 'Täsir eden URL',
    evidence: 'Subutnama',
    remediation: 'Çäre',
  },
  analytics: {
    title: 'Analitika',
    subtitle: 'Skanlamalar we zelelilikler boýunça trendler we hasabatlar.',
    trends: 'Zelelilik trendleri',
    commonIssues: 'Köp duş gelýän meseleler',
    scanSuccess: 'Skan üstünlik göterimi',
    riskHeatmap: 'Howp ýyladyş kartasy',
    timeReport: 'Wagt boýunça hasabat',
    from: 'Başlangyç',
    to: 'Son',
    noData: 'Maglumat ýok',
    bySeverity: 'Howp derejesi boýunça',
    byMonth: 'Aý boýunça',
  },
  schedules: {
    title: 'Skan tertipleri',
    subtitle: 'Yzygiderli skanlary meýilleşdiriň.',
    newSchedule: 'Täze tertip',
    targetIdLabel: 'Niýet ID',
    cronLabel: 'Cron formula',
    typeLabel: 'Skan görnüşi',
    nextRun: 'Indiki işleýiş',
    empty: 'Tertip ýok.',
    createFailed: 'Tertip döredilmedi.',
    devTools: 'Geliştirici gurallary',
    devToolsHint: 'Aşakdaky bölüm diňe admin/geliştirici üçin. Cron işçileri elden barlamak.',
    enqueueTitle: 'Tertip nobata goş',
    workerTitle: 'Worker döwrüni işlet',
    enqueueHint: 'Sanawdaky tertip ID-lerini nobata iberýär.',
    workerHint: 'Garaşýan tertipleri derrew işläp geçýär.',
    enqueue: 'Nobata goş',
    runWorker: 'Worker işlet',
    working: 'Işleýär…',
  },
  advanced: {
    title: 'Goşmaça skanlar',
    subtitle: 'Adaty skandan başga ýörite howpsuzlyk barlaglary.',
    apiScan: 'API skan',
    jwtCheck: 'JWT barlag',
    graphqlScan: 'GraphQL skan',
    headerAnalysis: 'Header analiz',
    aiSummary: 'AI gysga mazmun',
    apiScanDesc: 'API-ni umumy zelelilikler üçin barla.',
    jwtCheckDesc: 'JWT-i gowşak konfigurasiýa üçin barla.',
    graphqlScanDesc: 'GraphQL endpoint barla.',
    headerAnalysisDesc: 'HTTP howpsuzlyk başlyklaryny analizle.',
    aiSummaryDesc: 'Skan netijesini AI üsti bilen gysga mazmuna getir.',
    requestBody: 'Soraw göwresi',
    response: 'Jogap',
    run: 'Işlet',
    running: 'Işleýär…',
    noResponse: 'Henize çenli jogap ýok',
  },
  profile: {
    title: 'Profil',
    editProfile: 'Profili üýtget',
    usernameLabel: 'Ulanyjy ady',
    emailLabel: 'Email',
    phoneLabel: 'Telefon',
    saveFailed: 'Profil saklanmady.',
    apiKeys: 'API açarlary',
    newKey: 'Täze açar',
    noKeys: 'API açar ýok.',
    keyName: 'Açar ady',
    keyCreateFailed: 'Açar döretmek başartmady.',
    keyDeleteConfirm: 'Bu açary pozmak isleýärsiňizmi?',
    keyCreated: 'Açar döredildi',
    keySecretWarning: 'Bu açar diňe BIR GEZEK görkezilýär. Howpsuz ýere göçüriň — gaýdyp görmek mümkin däl!',
    copyKey: 'Açary göçür',
    keyCopied: 'Açar göçürildi',
    iSaved: 'Saklanyldy, dowam et',
  },
  admin: {
    usersTitle: 'Ulanyjylar',
    usersSubtitle: 'Ulanyjylary, rollary we niýet bermelerini dolandyryň.',
    editUser: 'Ulanyjyny üýtget',
    assignTarget: 'Niýet belle',
    targetIdLabel: 'Niýet ID',
    deleteUserConfirm: '{name} pozulsynmy?',
    saveFailed: 'Saklanyp bolmady.',
    assignFailed: 'Bellenip bolmady.',
    settingsTitle: 'Ulgam sazlamalary',
    settingsSubtitle: 'Açar/baha sazlamalary we ZAP skaner konfigurasiýasy.',
    newSetting: 'Täze sazlama',
    keyCol: 'Açar',
    valueCol: 'Baha',
    deleteSettingConfirm: '{key} pozulsynmy?',
    zapConfig: 'ZAP konfigurasiýasy',
    zapSaved: 'ZAP konfigurasiýasy saklandy.',
    noConfig: 'Konfigurasiýa ýok',
    updateCreate: 'Täzele / Döret',
    saveConfig: 'Konfigurasiýany sakla',
    auditTitle: 'Audit ýazgylary',
    auditSubtitle: 'Platforma tarapyndan ýazga alnan ähli admin hereketleri.',
    actionFilter: 'Hereket',
    actorFilter: 'Edýän',
    objectCol: 'Obýekt',
    detailsCol: 'Jikme-jiklikler',
    empty: 'Ýazgy ýok.',
    blogTitle: 'Blog ýazgylary',
    blogSubtitle: 'Çap edilen blog ýazgylaryny döret, üýtget we poz.',
    newPost: 'Täze ýazgy',
    titleLabel: 'Ady',
    tagsLabel: 'Teglar (otur bilen)',
    contentLabel: 'Mazmuny',
    authorCol: 'Awtor',
    publishedCol: 'Çap edildi',
    deletePostConfirm: '"{title}" pozulsynmy?',
    docsTitle: 'Dokumentasiýa sahypalary',
    docsSubtitle: 'Açyk dokumentasiýa sahypalaryny dolandyr.',
    newPage: 'Täze sahypa',
    slugLabel: 'Slug',
    categoryLabel: 'Kategoriýa',
    deletePageConfirm: '"{title}" pozulsynmy?',
    noPosts: 'Heniz ýazgy ýok.',
    noPages: 'Heniz sahypa ýok.',
    noUsers: 'Ulanyjy ýok.',
    noSettings: 'Sazlama ýok.',
  },
  dashboard: {
    activeScans: 'Aktiw skanlar',
    totalTargets: 'Jemi niýetler',
    criticalVulns: 'Kritiki zelelilikler',
    securityScore: 'Howpsuzlyk bali',
    recentScans: 'Soňky skanlar',
    viewAll: 'Hemmesini gör',
    noScans: 'Heniz skan ýok.',
    secureDomain: 'Domeniňizi gora',
    secureDomainHint: 'Täze niýet goşuň we awtomatik skanlamaga başlaň.',
    addTarget: 'Niýet goş',
    commonIssues: 'Köp duş gelýän meseleler',
  },
  system: {
    title: 'Ulgam',
    subtitle: 'Backend shema we API dokumentasiýasy.',
    openapi: 'OpenAPI shema',
    apiDocs: 'API dokumentasiýasy',
    apiConsole: 'API konsol',
    apiConsoleSubtitle: 'UI-den ähli backend endpointini çagyrmak üçin gural. Diňe admin.',
    requestInputs: 'Soraw maglumatlary',
    requestBody: 'Soraw göwresi',
    lastCall: 'Soňky çagyryş',
    response: 'Jogap',
    statusReady: 'Taýýar',
    statusRunning: 'Soraw işleýär…',
    copyJson: 'JSON göçür',
    noResponse: 'Heniz jogap ýok',
    noneYet: 'Henize çenli ýok',
  },
  blog: {
    title: 'Howpsuzlyk täzelikleri we bloglar',
    subtitle: 'Web howpsuzlyk pudagyndan iň soňky habarlar, trendler we sapaklar.',
    loadFailed: 'Blog ýazgylaryny ýüklemek başartmady.',
    showing: 'Görkezilýär',
    results: 'netije',
  },
  docs: {
    selectPage: 'Sahypa saýlaň',
    general: 'Umumy',
  },
  home: {
    heroTitle1: 'Häzirki zaman programmalaryňyzy',
    heroTitleAccent: 'GORAŇ.',
    heroTitle2: 'Howpsuzlygy AWTOMATLAŞDYRYŇ',
    heroSubtitle: 'Web howpsuzlyk platformamyz bilen zeleliligi tap, kody gora we sanly emläkleriňizi gora.',
    getStarted: 'Başla',
    viewDocs: 'Dokumentasiýany gör',
    featuresTitle: 'Esasy aýratynlyklar',
    feature1Title: 'Awtomatik skanlama',
    feature1Desc: 'Her commit-de zelelilikler üçin repozitoriýalary awtomatik skanlaýar.',
    feature2Title: 'Real-time gorag',
    feature2Desc: 'Howplary ulanyjylara ýetmänkä monitorla we bloklat.',
    feature3Title: 'Komplaýans hasabatlary',
    feature3Desc: 'Stakeholders üçin derrew howpsuzlyk we komplaýans hasabatlary döret.',
    feature4Title: 'API howpsuzlygy',
    feature4Desc: 'API-leriňizi we endpointleriňizi inýeksiýa hüjümlerden gora.',
  },
  errors: {
    generic: 'Bir säwlik ýüze çykdy.',
    network: 'Tor säwligi. Internet baglanyşygyňyzy barlaň.',
    unauthorized: 'Rugsat ýok. Täzeden giriş ediň.',
    forbidden: 'Bu hereket üçin hakyňyz ýok.',
    notFound: 'Tapylmady.',
    server: 'Server säwligi. Soň synanyşyň.',
  },
} as const

export type Strings = typeof tk

export const t = tk

export const tx = (template: string, vars: Record<string, string | number>): string => {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`))
}
